---

- name: Install essentials
  sudo: yes
  apt: pkg=$item state=latest install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - python-pip
    - python-dev
    - build-essential
    - cmake
    - python-apt
    - software-properties-common
