---

- name: add postgresql repo
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

- name: install postgres and psycopg2
  sudo: yes
  apt: pkg=$item state=latest force=yes install_recommends=no 
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
