---

- name: add postgresql repo
      action: apt_repository repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

- name: install postgres and psycopg2
  apt: pkg=$item state=latest install_recommends=no
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
