---

- name: add postgresql repo
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

- name: install postgres and psycopg2
  sudo: yes
  apt: pkg=$item state=latest force=yes install_recommends=no 
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Allow peer auth for TCP connections to postgres
  sudo: yes
  lineinfile: dest=/etc/postgresql/9.2/main/pg_hba.conf regexp="^host    all             all             127.0.0.1/32            md5:" insertafter=EOF line="host    all             all             127.0.0.1/32            trust"
  notify:
    - restart postgresql

- name: Create a new database
  sudo_user: postgres
  postgresql_db: db=$db_name

- name: Create database user and grant access to database and tables
  sudo_user: postgres
  postgresql_user: db=db_name user=db_user password=db_password priv=ALL
