---

- name: add postgresql repo
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

- name: install postgres and psycopg2
  sudo: yes
  apt: pkg=$item state=latest force=yes install_recommends=no 
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2

- name: Create a new database
  postgresql_db: db=$db_name

- name: Create database user and grant access to database and tables
  postgresql_user: db=db_name user=db_user password=db_password priv=ALL
